.PHONY: clean All

All:
	@echo "----------Building project:[ RF24WebSocket - Debug ]----------"
	@cd "RF24WebSocket" && "$(MAKE)" -f  "RF24WebSocket.mk"
clean:
	@echo "----------Cleaning project:[ RF24WebSocket - Debug ]----------"
	@cd "RF24WebSocket" && "$(MAKE)" -f  "RF24WebSocket.mk" clean
